### ISSUE TITLE
No Documentation. Usage unclear

### ISSUE THREAD

**Issue by rtizzy** [tmathmeyer/netmenu#1]
Greetings, 

I've looked around but have found no documentation for this tool. I've attempted to run it using "netmenu" but it simply provides a blank dmenu screen at the top of i3 with no additional text displayed. netmenu --help is simply passes through to dmenu. 

Any guidance appreciated. 

Thanks!

**Comment by tmathmeyer** [comment]
Yes, I probably should write up some documentation. I'm currently pretty busy with school, but I can try to help you solve the immediate issue at hand.
what is the output of netctldlist?

**Comment by rtizzy** [comment]
~ ❯❯❯ netmenu                                                                                                                                                ⏎
Trying to connect...
connect: No such file or directory
~ ❯❯❯ netctldlist                                                                                                                                            ⏎
~ ❯❯❯

**Comment by tmathmeyer** [comment]
you have to start the systemctl deamon
$ systemctl start netmenu.service (as root)

if you dont use systemd, then you can just run the 'netctld' binary as a normal user in either your init system or manually after booting

**Comment by rijkt** [comment]
Found this project linked on the arch wiki. Installed it, started it and I was immediately lost. There's no README, no wiki and `netmenu --help` doesn't explain the parameters. Starting the netmenu service still does not tell me how to use the program. 

I would really like to give this a shot, so please add or link some minimal usage guide, @tmathmeyer .
